### ISSUE TITLE
bug/coroutine-await

### ISSUE THREAD

**Issue by tluthra** [Unstructured-IO/unstructured-python-client#149]
**Describe the bug**
i'm currently using the open source version of unstructured, and getting an exception about `coroutine is being awaited already`. This causes the parse to fail, and not work.

**To Reproduce**
It just seems to happen every so often, I'm not sure how to reproduce it. It's not on the same files, if I retry them, they'll succeed. I am putting a lot of files + data through the system, but nothing that seems to be something it shouldnt be able to handle.

**Expected behavior**
Not get this error.

**Screenshots**
N/A

**Environment Info**
I'm pullling `downloads.unstructured.io/unstructured-io/unstructured-api:latest` as my container and just running this.
Also running `unstructured-client = "^0.23.8"` on my client side.

**Additional context**
There's also a few warning that are showing up related to coroutines too:
```
[2024-08-08 17:10:50,239: WARNING/MainProcess] /home/appuser/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.11/lib/python3.11/site-packages/unstructured_client/_hooks/custom/split_pdf_hook.py:202: RuntimeWarning: coroutine 'SplitPdfHook.before_request.<locals>.call_api_partial' was never awaited
  self.coroutines_to_execute[operation_id] = []
  ```
  
  ```
  [2024-08-08 17:47:48,365: WARNING/MainProcess] Traceback (most recent call last):
[2024-08-08 17:47:48,365: WARNING/MainProcess]   File "<string>", line 1, in <lambda>
[2024-08-08 17:47:48,365: WARNING/MainProcess] KeyError
[2024-08-08 17:47:48,365: WARNING/MainProcess] :
[2024-08-08 17:47:48,365: WARNING/MainProcess] '__import__'
[2024-08-08 17:47:48,366: WARNING/MainProcess] Exception ignored in:
[2024-08-08 17:47:48,366: WARNING/MainProcess] <coroutine object SplitPdfHook.before_request.<locals>.call_api_partial at 0x7f4753372480> 
```

**Comment by tluthra** [comment]
```
[2024-08-08 22:45:35,624: ERROR/MainProcess] Task exception was never retrieved
future: <Task finished name='Task-189' coro=<_wrapped_create_task_py37.<locals>.traced_coro() done, defined at /home/appuser/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.11/lib/python3.11/site-packages/ddtrace/contrib/asyncio/patch.py:47> exception=RuntimeError('coroutine is being awaited already')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/appuser/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.11/lib/python3.11/site-packages/ddtrace/contrib/asyncio/patch.py", line 50, in traced_coro
    return await coro
           ^^^^^^^^^^
  File "/home/appuser/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.11/lib/python3.11/site-packages/unstructured_client/_hooks/custom/split_pdf_hook.py", line 49, in _order_keeper
    response = await coro
               ^^^^^^^^^^
RuntimeError: coroutine is being awaited already
[2024-08-08 22:45:35,639: ERROR/MainProcess] Task exception was never retrieved
future: <Task finished name='Task-188' coro=<_wrapped_create_task_py37.<locals>.traced_coro() done, defined at /home/appuser/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.11/lib/python3.11/site-packages/ddtrace/contrib/asyncio/patch.py:47> exception=RuntimeError('coroutine is being awaited already')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/appuser/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.11/lib/python3.11/site-packages/ddtrace/contrib/asyncio/patch.py", line 50, in traced_coro
    return await coro
           ^^^^^^^^^^
  File "/home/appuser/.cache/pypoetry/virtualenvs/app-9TtSrW0h-py3.11/lib/python3.11/site-packages/unstructured_client/_hooks/custom/split_pdf_hook.py", line 49, in _order_keeper
    response = await coro
               ^^^^^^^^^^
RuntimeError: coroutine is being awaited already
```

this is a more full exception stack I'm getting here

**Comment by awalker4** [comment]
Hi @tluthra - just want to let you know that this is on our radar! The next release of the SDK will provide much better asyncio support, and I'm chasing down these sorts of errors now.

**Comment by tluthra** [comment]
@awalker4 appreciate the update, until then is there anything you can suggest as a work around?

**Comment by awalker4** [comment]
For now, you can sidestep the async code by running with `split_pdf_page=False`. If you are working with very large pdfs, and you still need to split up the file before sending, the next thing to try is `split_pdf_allow_failed=True`. We've identified some bugs when this option is False, which means stop processing the doc if any of the underlying splits hits an error. It seems there's some asyncio cleanup that isn't happening in this path.

**Comment by awalker4** [comment]
Also, can I see how you are calling the client? Just to make sure I can reproduce all of the asyncio warnings here.

**Comment by tluthra** [comment]
yea, I'm using it like this:
```
        with open(local_filename, "rb") as f:
            files = shared.Files(
                content=f.read(),
                file_name=local_filename,
            )

            req = shared.PartitionParameters(
                files=files,
                strategy="auto",
                languages=["eng"],
                chunking_strategy=ChunkingStrategy.BY_TITLE,
                combine_under_n_chars=2500,
                max_characters=3000,
                overlap=250,
            )
            resp = cls._client.general.partition(req)

```

**Comment by tluthra** [comment]
@awalker4 did this ever get fixed? I'm revisiting this in my code, and having issues with large pdfs not being split and disconnecting from the server
